#!/command/with-contenv bash

source /assets/functions/00-container
set -a
prepare_service
PROCESS_NAME="headscale"
set +a
setup_container_mode
bootstrap_filesystem

if [ ! -f "/tmp/.container/container-restart" ] ; then
    if var_true "${ENABLE_CLIENT}" ; then
        print_debug "Configuring Client"
    else
        service_stop headscale-client
    fi

    if var_true "${ENABLE_SERVER}" ; then
        print_debug "Configuring Server"
        configure_server
    else
        service_stop headscale-server
    fi

    if var_true "${ENABLE_UI}" ; then
        print_debug "Configuring UI"
        configure_ui
    else
        service_stop 10-nginx
        service_stop 11-nginx-config-reload
        rm -rf /etc/zabbix/zabbix_agentd.conf.d/nginx.conf
    fi

    if var_true "${ENABLE_STANDALONE}" ; then
        print_debug "Configuring Standlone"
        liftoff
        exit 0
    fi

headscale completion bash >> /root/.bashrc
fi

liftoff
