#!/command/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="headscale-client"
source /assets/defaults/10-headscale
source /assets/functions/10-headscale
check_container_initialized

liftoff

print_start "Starting Headscale Client ${HEADSCALE_VERSION}"
#silent exec setuidgid headscale \
#                                headscale
sleep 86400
